[project]
name = "everydaylog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agentscope>=1.0.10",
    "opencv-python>=4.12.0.88",
    "pillow>=12.1.0",
    "pyautogui>=0.9.54",
    "pydantic>=2.12.5",
    "pyside6>=6.10.1",
    "pyside6-fluent-widgets[full]>=1.10.5",
    "rtoml>=0.13.0",
    "sqlalchemy>=2.0.45",
]
